### PR TITLE
PeerJS client failing to connect to server

### LINKED ISSUE #28: PeerJS client failing to connect to server
### What is the problem?
_When the **eighth** PeerJS client connection is made the video feed stutters leading to the freezing of the WebRTC call._  litlmoz/pinto#15

_**Expected** - Occurs after entering room & before joining call_
```
./node_modules/peerjs/dist/peerjs.min.js
Critical dependency: the request of a dependency is an expression
```
_**Unknown** - After joining the fifth call & before server logs disconnect_
```
Can’t establish a connection to the server at wss://pintopinto.herokuapp.com/pinto.io/?EIO=4&transport=websocket&sid=-VehyHxL1X5rv_lnAAAS.
```
_**Culprit** - After PeerJS logs `iceConnectionState change to disconnected`_
```
WebRTC: ICE failed, your TURN server appears to be broken
```

### Steps to Reproduce
- [ ] Load **eight** tabs of the same room & join **two** calls.
> Opens **two** WebRTC connections & **eight** PeerClient connections.
- [ ] Load **seven** tabs of the same room & joining each call.
> Opens **seven** WebRTC connections & **seven** PeerClient connections. Emitting socket.io message to answer PeerJS's WebRTC invite to stream video.

**Expected**
> Load **seven** or **eight** tabs without video call freezing

### Versions:
Server
```
socket.io:  3.1.1
peer:       0.6.1
stack:      Heroku-20
Node.js:    15.8.0
```
Client
```
socket.io-client: 3.1.1
peerjs:           1.3.1
stack:    Next.js 10.0.6
LTS Node.js:      14.15.5
```

### PR DESCRIPTION
**Pull request by soliskit**
Fix #28 

[GitKraken Card](https://app.gitkraken.com/glo/view/card/a12d02e556d74ff481ebbea74cc2dc38)

### CODE REVIEW

File: usePeerState.ts [hunk 1]
```diff
@@ -18,7 +18,12 @@ const usePeerState = (
           const peerOptions: Peer.PeerJSOption = {
             key: process.env.NEXT_PUBLIC_KEY,
             host: process.env.NEXT_PUBLIC_HOST,
-            debug: 2
```
Comment (soliskit) [inline usePeerState.ts:21]: revert back to 2
> Prints errors and warnings.
